//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORRECAO_PROVA_OFICIAL_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Prova_Oficial2_CorrecaoEntities : DbContext
    {
        public Prova_Oficial2_CorrecaoEntities()
            : base("name=Prova_Oficial2_CorrecaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profissao> Profissao { get; set; }
        public virtual DbSet<Profissional> Profissional { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
