//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORRECAO_PROVA_OFICIAL_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profissao()
        {
            this.Profissional = new HashSet<Profissional>();
        }
    
        public int ProfissaoId { get; set; }
        public string NomeProfissao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profissional> Profissional { get; set; }
    }
}
