//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORRECAO_PROVA_OFICIAL_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissional
    {
        public int ProfissionalId { get; set; }
        public string NomeProfissional { get; set; }
        public int ProfissaoId { get; set; }
    
        public virtual Profissao Profissao { get; set; }
    }
}
